# Site settings
title: NOT EVEN JOKING
description: "Lowkey portefolio"
baseurl: "/NOT-EVEN-JOKING" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Pierre
user_title: "Let's go pierre"
email: p.assamoi@gmail.com
twitter_username: PierreASM
github_username:  Passamoi
gplus_username:  P.assamoi
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: "Let's go Pierre"
profile_picture: https://i.ibb.co/T19Qvxk/tofglitch.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /NOT-EVEN-JOKING
      key_trigger: 1
    - title: my posts
      url: /NOT-EVEN-JOKING/posts
      key_trigger: 2
    - title: series
      url: /NOT-EVEN-JOKING/series
      key_trigger: 3
    - title: tags
      url: /NOT-EVEN-JOKING/tags
      key_trigger: 4
    - title: about me
      url: /NOT-EVEN-JOKING/about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/Passamoi/
      new_tab: true
      key_trigger: g
    - title: twitter
      url: https://twitter.com/PierreASM
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
